#pragma once
#ifndef __HEADER_BUFFER_CACHE_CONFIG__
    #define __HEADER_BUFFER_CACHE_CONFIG__
    #define EVICTION_FLUSH_TYPE_SINGLE_FLUSH_THREAD 0
    #define EVICTION_FLUSH_TYPE_THREAD_POOL 1

    /*
    #define REPLACEMENT_POLICY_TYPE_FIFO 0
    #define REPLACEMENT_POLICY_TYPE_LFU 1
    #define REPLACEMENT_POLICY_TYPE_LRU 2
    
    */
    #define CONFIG_REPLACEMENT_POLICY_TYPE 0
    #define CONFIG_TOTAL_N 1024
    #define CONFIG_MANANAGEABLE_N 500
    #define USE_MMAP_RW 1
    /**
    #define RANDOM_DISTRIBUTION_TYPE_PURE 0
    #define RANDOM_DISTRIBUTION_TYPE_NORMAL 1
    #define RANDOM_DISTRIBUTION_TYPE_ZIPFIAN 2
    */
    #define CONFIG_RANDOM_DISTIRUBUTION_TYPE 2
    #define CONFIG_RANDOM_ACCESS_SEQUENCE_MAX_VALUE 1023
    #define CONFIG_RANDOM_ACCESS_SEQUENCE_ELEMENT_COUNT 10000
    #define CONFIG_RANDOM_WRITE_COUNT 10000
    
    #define CONFIG_EVICTION_FLUSH_TYPE 0
    #define CONFIG_THREAD_POOL_NUMBER_OF_INTERNAL_THREAD 3
    #define CONFIG_THREAD_POOL_NUMBER_OF_PACKET_SIZE_FOR_MEMORY_BUFFER 50
    #define CONFIG_DEBUG_MODE 0
    
#endif